- name: Linux pre-requisites
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: apt install
      apt:
        update_cache: yes
        name:
          - neovim
          - git
          - bat 
          - tmux
          - rsync
          - ripgrep
          - dnsutils

- name: Proxy / HTTP things
  hosts: proxy
  gather_facts: false
  tasks:
    - name: apt install
      apt:
        update_cache: yes
        name:
          - iptables-persistent
          - wireguard
          - merecat
          - runit
          - ifupdown
    - name: ipv4 firewall
      copy:
        src: proxy.iptables.v4
        dest: /etc/iptables/rules.v4
      notify: "reload firewall"
    - name: wireguard config
      copy:
        src: proxy.wg0.conf
        dest: /etc/wireguard/wg0.conf
        mode: 0600
      notify: "restart wg0"
    - name: enable wg0
      service:
        name: "wg-quick@wg0"
        enabled: true
    - name: configure merecat
      copy:
        src: proxy.merecat.conf
        dest: /etc/merecat.conf
      notify: "restart merecat"
    - name: create www user
      user:
        name: www
        group: www-data
        shell: /bin/bash
        create_home: yes
    - name: www SSH directory
      file:
        path: /home/www/.ssh
        state: directory
        mode: 0700
        owner: www
    - name: www SSH key
      copy:
        src: authorized_keys
        dest: /home/www/.ssh/authorized_keys
        mode: 0600
        owner: www
        directory_mode: 0700
    - name: permission on /var/www
      file:
        path: /var/www
        owner: www
        group: www-data
        mode: 0755
    - name: traefik directory
      copy:
        src: proxy.traefik/
        dest: /root/traefik/
        mode: preserve
    - name: traefik service directory
      copy:
        src: proxy.traefik-sv/
        dest: /etc/service/traefik/
        mode: preserve
  handlers:
    - name: reload firewall
      shell: "/etc/init.d/netfilter-persistent reload"
    - name: restart wg0
      shell: "systemctl restart wg-quick@wg0"
    - name: restart merecat
      shell: "systemctl daemon-reload && systemctl restart merecat"
