- name: Linux pre-requisites
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: apt install
      apt:
        update_cache: yes
        name:
          - neovim
          - git
          - bat 
          - tmux
          - rsync
          - ripgrep
          - dnsutils

- name: Proxy / HTTP things
  hosts: proxy
  gather_facts: false
  tasks:
    - name: apt install
      apt:
        update_cache: yes
        name:
          - iptables-persistent
          - wireguard
          - merecat
    - name: ipv4 firewall
      copy:
        src: proxy.iptables.v4
        dest: /etc/iptables/rules.v4
      notify: "reload firewall"
  handlers:
    - name: reload firewall
      shell: "/etc/init.d/netfilter-persistent reload"
