providers:
  file:
    filename: "traefik-provider.yaml"
    watch: true
entryPoints:
  ep443:
    address: :443
  ep80:
    address: :80
    http:
      redirections:
        entryPoint:
          to: "ep443"
certificatesResolvers:
  resolver0:
    acme:
      email: aaron@insom.me.uk
      storage: acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 0
  resolver1:
    acme:
      email: aaron@insom.me.uk
      storage: acme.json
      httpChallenge:
        entrypoint: ep80
